// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

import '../../domain/entities/common_entity.dart';
import '../../domain/repositories/common_repository.dart';
import '../datasources/common_remote_data_source.dart';
import '../models/common_model.dart';

class CommonRepositoryImpl implements CommonRepository {
  const CommonRepositoryImpl(this.dataSource);

  final CommonRemoteDataSource dataSource;

  @override
  Future<CommonEntity> get() async {
    final json = await dataSource.fetch();
    return CommonModel.fromJson(json);
  }
}
