// GENERATED FILE - DO NOT EDIT BY HAND
// Generated by design_codegen from the Galaxy Figma plugin tokens JSON.

import 'package:flutter/material.dart';
import 'package:design_system/design_system.dart';
import '../../../../../generated/routes/app_router.dart';
import '../../../../../generated/constants/assets_path.dart';

class ClientProfile extends StatelessWidget {
  const ClientProfile({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: context.ds.backgroundPrimary,
      body: SafeArea(
        child: SingleChildScrollView(
          child: Container(
          decoration: BoxDecoration(
            color: const Color(0xFF08090C),
          ),
          child: Column(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Row(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                SizedBox(
                  width: 260.0,
                  child: Container(
                  padding: const EdgeInsets.fromLTRB(16.0, 24.0, 16.0, 24.0),
                  decoration: BoxDecoration(
                    color: const Color(0xFF12141C),
                    border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                  ),
                  child: Column(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Padding(
                      padding: const EdgeInsets.fromLTRB(12.0, 0.0, 0.0, 28.0),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        SizedBox(
                          width: 28.0,
                          height: 28.0,
                          child: Container(
                          decoration: BoxDecoration(
                            color: const Color(0xFFD2FF00),
                            borderRadius: BorderRadius.circular(RadiusTokens.radius6),
                          ),
                          child: Column(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                          ],
                        ),
                        ),
                        ),
                        const SizedBox(width: 8.0),
                        AppText(
                          'FitPro',
                          style: TextStyle(color: context.ds.textPrimary, fontFamily: 'Outfit', fontSize: 20.0, letterSpacing: -1.0),
                          textAlign: TextAlign.left,
                        ),
                        const SizedBox(width: 8.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(6.0, 2.0, 6.0, 2.0),
                          decoration: BoxDecoration(
                            color: const Color(0x12FFFFFF),
                            borderRadius: BorderRadius.circular(RadiusTokens.radius4),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText(
                              'SaaS',
                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 10.0),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                      ],
                    ),
                    ),
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Diet Plan',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Workouts Programs',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Progress Sharing',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Client Management',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Subscription',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                          decoration: BoxDecoration(
                            color: const Color(0x1AD2FF00),
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Client Profile',
                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist', fontSize: 14.0),
                              textAlign: TextAlign.left,
                            ),
                            const SizedBox(width: 12.0),
                            Container(
                              width: 6.0,
                              height: 6.0,
                              decoration: BoxDecoration(
                                color: const Color(0xFFD2FF00),
                                shape: BoxShape.circle,
                              ),
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Leads Management',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Business Growth',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Unlimited Co-workers',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Custom Branding',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Reports',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 402.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 12.0, 12.0, 12.0),
                      decoration: BoxDecoration(
                        color: const Color(0x05FFFFFF),
                        borderRadius: BorderRadius.circular(RadiusTokens.radius12),
                        border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Image.asset(
                          rectangle31279,
                          width: 36.0,
                          height: 36.0,
                          fit: BoxFit.fill,
                        ),
                        const SizedBox(width: 12.0),
                        Expanded(child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText(
                              'Coach Marcus',
                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 13.0),
                              textAlign: TextAlign.left,
                            ),
                            const SizedBox(height: 2.0),
                            AppText(
                              'HEAD TRAINER',
                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        )),
                      ],
                    ),
                    ),
                  ],
                ),
                ),
                ),
                Expanded(child: Column(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Container(
                      padding: const EdgeInsets.fromLTRB(32.0, 16.0, 32.0, 16.0),
                      decoration: BoxDecoration(
                        border: Border(top: BorderSide.none, right: BorderSide.none, bottom: BorderSide(color: const Color(0xFF1C1F2B), width: 1.0), left: BorderSide.none),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText(
                              'Client Profile Portal',
                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 24.0),
                              textAlign: TextAlign.left,
                            ),
                            const SizedBox(height: 4.0),
                            AppText(
                              'Individual Coaching Dashboard & Client Dossier',
                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            SizedBox(
                              width: 220.0,
                              child: Container(
                              padding: const EdgeInsets.fromLTRB(12.0, 8.0, 12.0, 8.0),
                              decoration: BoxDecoration(
                                color: const Color(0x08FFFFFF),
                                borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                              ),
                              child: Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    const AppIcon(Icons.circle),
                                  ],
                                ),
                                const SizedBox(width: 8.0),
                                AppText(
                                  'Search...',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                              ],
                            ),
                            ),
                            ),
                            const SizedBox(width: 16.0),
                            SizedBox(
                              width: 36.0,
                              height: 36.0,
                              child: Container(
                              decoration: BoxDecoration(
                                color: const Color(0x05FFFFFF),
                                borderRadius: BorderRadius.circular(RadiusTokens.radius18),
                                border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                              ),
                              child: Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    const AppIcon(Icons.circle),
                                  ],
                                ),
                                Container(
                                  width: 8.0,
                                  height: 8.0,
                                  decoration: BoxDecoration(
                                    color: const Color(0xFFD2FF00),
                                    shape: BoxShape.circle,
                                    border: Border.all(color: const Color(0xFF12141C), width: 1.5),
                                  ),
                                ),
                              ],
                            ),
                            ),
                            ),
                            const SizedBox(width: 16.0),
                            Container(
                              padding: const EdgeInsets.fromLTRB(16.0, 8.0, 16.0, 8.0),
                              decoration: BoxDecoration(
                                color: const Color(0xFFD2FF00),
                                borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                              ),
                              child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    const AppIcon(Icons.circle),
                                  ],
                                ),
                                const SizedBox(width: 6.0),
                                AppText(
                                  'Quick Assign',
                                  style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.left,
                                ),
                              ],
                            ),
                            ),
                          ],
                        ),
                      ],
                    ),
                    ),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(32.0, 32.0, 32.0, 32.0),
                      child: Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        Container(
                          padding: const EdgeInsets.fromLTRB(24.0, 24.0, 24.0, 24.0),
                          decoration: BoxDecoration(
                            color: const Color(0xFF12141C),
                            borderRadius: BorderRadius.circular(RadiusTokens.radius16),
                            border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Image.asset(
                              rectangle31303,
                              width: 64.0,
                              height: 64.0,
                              fit: BoxFit.fill,
                            ),
                            const SizedBox(width: 20.0),
                            Expanded(child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      'Alex Rivera',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 22.0),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 12.0),
                                    Container(
                                      padding: const EdgeInsets.fromLTRB(8.0, 2.0, 8.0, 2.0),
                                      decoration: BoxDecoration(
                                        color: const Color(0x1AD2FF00),
                                        borderRadius: BorderRadius.circular(RadiusTokens.radius4),
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'ELITE MEMBER',
                                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    ),
                                  ],
                                ),
                                const SizedBox(height: 4.0),
                                AppText(
                                  'alex.rivera@procoaching.co • Active since Sep 2026',
                                  style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                              ],
                            )),
                            const SizedBox(width: 20.0),
                            Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Container(
                                  padding: const EdgeInsets.fromLTRB(14.0, 8.0, 14.0, 8.0),
                                  decoration: BoxDecoration(
                                    color: const Color(0x05FFFFFF),
                                    borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                    border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    AppText(
                                      'Edit Member Details',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                  ],
                                ),
                                ),
                                const SizedBox(width: 8.0),
                                Container(
                                  padding: const EdgeInsets.fromLTRB(14.0, 8.0, 14.0, 8.0),
                                  decoration: BoxDecoration(
                                    color: const Color(0xFFD2FF00),
                                    borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    AppText(
                                      'Assign Program',
                                      style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                  ],
                                ),
                                ),
                              ],
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 24.0),
                        Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Expanded(child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                Container(
                                  padding: const EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 20.0),
                                  decoration: BoxDecoration(
                                    color: const Color(0xFF12141C),
                                    borderRadius: BorderRadius.circular(RadiusTokens.radius16),
                                    border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                                  ),
                                  child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.stretch,
                                  children: [
                                    AppText(
                                      'Client Body Composition & Biometrics',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 16.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(height: 16.0),
                                    Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Expanded(child: Container(
                                          padding: const EdgeInsets.fromLTRB(12.0, 12.0, 12.0, 12.0),
                                          decoration: BoxDecoration(
                                            color: const Color(0xFF08090C),
                                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                            border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                                          ),
                                          child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              '84.1 kg',
                                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Outfit', fontSize: 18.0, fontWeight: FontWeight.w700),
                                              textAlign: TextAlign.left,
                                            ),
                                            const SizedBox(height: 4.0),
                                            AppText(
                                              'CURRENT WEIGHT',
                                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 11.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        )),
                                        const SizedBox(width: 12.0),
                                        Expanded(child: Container(
                                          padding: const EdgeInsets.fromLTRB(12.0, 12.0, 12.0, 12.0),
                                          decoration: BoxDecoration(
                                            color: const Color(0xFF08090C),
                                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                            border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                                          ),
                                          child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              '14.2%',
                                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Outfit', fontSize: 18.0, fontWeight: FontWeight.w700),
                                              textAlign: TextAlign.left,
                                            ),
                                            const SizedBox(height: 4.0),
                                            AppText(
                                              'BODY FAT',
                                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 11.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        )),
                                        const SizedBox(width: 12.0),
                                        Expanded(child: Container(
                                          padding: const EdgeInsets.fromLTRB(12.0, 12.0, 12.0, 12.0),
                                          decoration: BoxDecoration(
                                            color: const Color(0xFF08090C),
                                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                            border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                                          ),
                                          child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              '45.6 kg',
                                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Outfit', fontSize: 18.0, fontWeight: FontWeight.w700),
                                              textAlign: TextAlign.left,
                                            ),
                                            const SizedBox(height: 4.0),
                                            AppText(
                                              'SKELETAL MUSCLE',
                                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 11.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        )),
                                        const SizedBox(width: 12.0),
                                        Expanded(child: Container(
                                          padding: const EdgeInsets.fromLTRB(12.0, 12.0, 12.0, 12.0),
                                          decoration: BoxDecoration(
                                            color: const Color(0xFF08090C),
                                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                            border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                                          ),
                                          child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              '58.1 L',
                                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Outfit', fontSize: 18.0, fontWeight: FontWeight.w700),
                                              textAlign: TextAlign.left,
                                            ),
                                            const SizedBox(height: 4.0),
                                            AppText(
                                              'TOTAL BODY WATER',
                                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 11.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        )),
                                      ],
                                    ),
                                  ],
                                ),
                                ),
                                const SizedBox(height: 20.0),
                                Container(
                                  padding: const EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 20.0),
                                  decoration: BoxDecoration(
                                    color: const Color(0xFF12141C),
                                    borderRadius: BorderRadius.circular(RadiusTokens.radius16),
                                    border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                                  ),
                                  child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.stretch,
                                  children: [
                                    AppText(
                                      'Client Attendance Track (Last 4 Weeks)',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 16.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(height: 16.0),
                                    Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'M',
                                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 10.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.center,
                                            ),
                                            const SizedBox(width: 8.0),
                                            AppText(
                                              'T',
                                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 10.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.center,
                                            ),
                                            const SizedBox(width: 8.0),
                                            AppText(
                                              'W',
                                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 10.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.center,
                                            ),
                                            const SizedBox(width: 8.0),
                                            AppText(
                                              'T',
                                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 10.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.center,
                                            ),
                                            const SizedBox(width: 8.0),
                                            AppText(
                                              'F',
                                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 10.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.center,
                                            ),
                                            const SizedBox(width: 8.0),
                                            AppText(
                                              'S',
                                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 10.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.center,
                                            ),
                                            const SizedBox(width: 8.0),
                                            AppText(
                                              'S',
                                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 10.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.center,
                                            ),
                                          ],
                                        ),
                                        const SizedBox(height: 10.0),
                                        Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              crossAxisAlignment: CrossAxisAlignment.start,
                                              children: [
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFF1C1F2B),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                              ],
                                            ),
                                            const SizedBox(height: 6.0),
                                            Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              crossAxisAlignment: CrossAxisAlignment.start,
                                              children: [
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFF1C1F2B),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFF1C1F2B),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                              ],
                                            ),
                                            const SizedBox(height: 6.0),
                                            Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              crossAxisAlignment: CrossAxisAlignment.start,
                                              children: [
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFF1C1F2B),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFF1C1F2B),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                              ],
                                            ),
                                            const SizedBox(height: 6.0),
                                            Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              crossAxisAlignment: CrossAxisAlignment.start,
                                              children: [
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFF1C1F2B),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFF1C1F2B),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                                const SizedBox(width: 8.0),
                                                Container(
                                                  width: 18.0,
                                                  height: 18.0,
                                                  decoration: BoxDecoration(
                                                    color: const Color(0xFFD2FF00),
                                                    borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ],
                                        ),
                                      ],
                                    ),
                                  ],
                                ),
                                ),
                              ],
                            )),
                            const SizedBox(width: 20.0),
                            Expanded(child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                Container(
                                  padding: const EdgeInsets.fromLTRB(4.0, 4.0, 4.0, 4.0),
                                  decoration: BoxDecoration(
                                    color: const Color(0xFF12141C),
                                    borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                    border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Expanded(child: Container(
                                      padding: const EdgeInsets.fromLTRB(0.0, 8.0, 0.0, 8.0),
                                      decoration: BoxDecoration(
                                        color: const Color(0xFF08090C),
                                        borderRadius: BorderRadius.circular(RadiusTokens.radius6),
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Program Activity',
                                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist', fontSize: 13.0),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    )),
                                    const SizedBox(width: 4.0),
                                    Expanded(child: Padding(
                                      padding: const EdgeInsets.fromLTRB(0.0, 8.0, 0.0, 8.0),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Training History',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    )),
                                    const SizedBox(width: 4.0),
                                    Expanded(child: Padding(
                                      padding: const EdgeInsets.fromLTRB(0.0, 8.0, 0.0, 8.0),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Billing & Invoices',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    )),
                                  ],
                                ),
                                ),
                                const SizedBox(height: 20.0),
                                Container(
                                  padding: const EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 20.0),
                                  decoration: BoxDecoration(
                                    color: const Color(0xFF12141C),
                                    borderRadius: BorderRadius.circular(RadiusTokens.radius16),
                                    border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                                  ),
                                  child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.stretch,
                                  children: [
                                    Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        AppText(
                                          'Assigned Program Tracker',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 16.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                        AppText(
                                          '65% Complete',
                                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 12.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    const SizedBox(height: 16.0),
                                    Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.stretch,
                                      children: [
                                        Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              '12-Week Premium Powerbuilding V3',
                                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 18.0, fontWeight: FontWeight.w700),
                                              textAlign: TextAlign.left,
                                            ),
                                            const SizedBox(height: 4.0),
                                            AppText(
                                              'Phase 2: High Volume accessory load',
                                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        const SizedBox(height: 12.0),
                                        SizedBox(
                                          height: 6.0,
                                          child: Container(
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(
                                            color: const Color(0x05FFFFFF),
                                            borderRadius: BorderRadius.circular(RadiusTokens.radius3),
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.max,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Container(
                                              width: 340.0,
                                              height: 6.0,
                                              decoration: BoxDecoration(
                                                color: const Color(0xFFD2FF00),
                                              ),
                                            ),
                                          ],
                                        ),
                                        ),
                                        ),
                                        const SizedBox(height: 12.0),
                                        Container(
                                          padding: const EdgeInsets.fromLTRB(12.0, 12.0, 12.0, 12.0),
                                          decoration: BoxDecoration(
                                            color: const Color(0xFFD2FF00),
                                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.max,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Modify Prescriptions',
                                              style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w700),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                      ],
                                    ),
                                  ],
                                ),
                                ),
                              ],
                            )),
                          ],
                        ),
                      ],
                    ),
                    ),
                  ],
                )),
              ],
            ),
          ],
        ),
        ),
        ),
      ),
    );
  }
}
