// GENERATED FILE - DO NOT EDIT BY HAND
// Generated by design_codegen from the Galaxy Figma plugin tokens JSON.

import 'package:flutter/material.dart';
import 'package:design_system/design_system.dart';
import '../../../../../generated/routes/app_router.dart';
import '../../../../../generated/constants/assets_path.dart';

class ClientManagement extends StatelessWidget {
  const ClientManagement({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: context.ds.backgroundPrimary,
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Row(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                SizedBox(
                  width: 260.0,
                  child: Padding(
                  padding: const EdgeInsets.fromLTRB(
                    16.0,
                    24.0,
                    16.0,
                    24.0,
                  ),
                  child: Column(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        0.0,
                        0.0,
                        28.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        SizedBox(
                          width: 28.0,
                          height: 28.0,
                          child: Column(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(width: 8.0),
                        AppText(
                          'FitPro',
                          style: TextStyle(color: AliasTokens.textPrimary, fontFamily: 'Outfit', fontSize: 20.0, letterSpacing: -1.0),
                          textAlign: TextAlign.left,
                        ),
                        const SizedBox(width: 8.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            6.0,
                            2.0,
                            6.0,
                            2.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText(
                              'SaaS',
                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 10.0),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                      ],
                    ),
                    ),
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            10.0,
                            12.0,
                            10.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Diet Plan',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            10.0,
                            12.0,
                            10.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Workouts Programs',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            10.0,
                            12.0,
                            10.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Progress Sharing',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            10.0,
                            12.0,
                            10.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Client Management',
                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist', fontSize: 14.0),
                              textAlign: TextAlign.left,
                            ),
                            const SizedBox(width: 12.0),
                            const SizedBox.shrink(),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            10.0,
                            12.0,
                            10.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Subscription',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            10.0,
                            12.0,
                            10.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Client Profile',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            10.0,
                            12.0,
                            10.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Leads Management',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            10.0,
                            12.0,
                            10.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Business Growth',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            10.0,
                            12.0,
                            10.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Unlimited Co-workers',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            10.0,
                            12.0,
                            10.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Custom Branding',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(height: 4.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            10.0,
                            12.0,
                            10.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 12.0),
                            AppText(
                              'Reports',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 402.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        12.0,
                        12.0,
                        12.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Image.asset(
                          rectangle3832,
                          width: 36.0,
                          height: 36.0,
                          fit: BoxFit.fill,
                        ),
                        const SizedBox(width: 12.0),
                        Expanded(child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText(
                              'Coach Marcus',
                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 13.0),
                              textAlign: TextAlign.left,
                            ),
                            const SizedBox(height: 2.0),
                            AppText(
                              'HEAD TRAINER',
                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        )),
                      ],
                    ),
                    ),
                  ],
                ),
                ),
                ),
                Expanded(child: Column(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        32.0,
                        16.0,
                        32.0,
                        16.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText(
                              'Client Roster',
                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 24.0),
                              textAlign: TextAlign.left,
                            ),
                            const SizedBox(height: 4.0),
                            AppText(
                              'Operator Dashboard • Client Management',
                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            SizedBox(
                              width: 220.0,
                              child: Padding(
                              padding: const EdgeInsets.fromLTRB(
                                12.0,
                                8.0,
                                12.0,
                                8.0,
                              ),
                              child: Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    const AppIcon(Icons.circle),
                                  ],
                                ),
                                const SizedBox(width: 8.0),
                                AppText(
                                  'Search client database...',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                              ],
                            ),
                            ),
                            ),
                            const SizedBox(width: 16.0),
                            SizedBox(
                              width: 36.0,
                              height: 36.0,
                              child: Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    const AppIcon(Icons.circle),
                                  ],
                                ),
                                const SizedBox.shrink(),
                              ],
                            ),
                            ),
                            const SizedBox(width: 16.0),
                            Padding(
                              padding: const EdgeInsets.fromLTRB(
                                16.0,
                                8.0,
                                16.0,
                                8.0,
                              ),
                              child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    const AppIcon(Icons.circle),
                                  ],
                                ),
                                const SizedBox(width: 6.0),
                                AppText(
                                  'Quick Assign',
                                  style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.left,
                                ),
                              ],
                            ),
                            ),
                          ],
                        ),
                      ],
                    ),
                    ),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        32.0,
                        32.0,
                        32.0,
                        32.0,
                      ),
                      child: Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Expanded(child: Padding(
                              padding: const EdgeInsets.fromLTRB(
                                16.0,
                                16.0,
                                16.0,
                                16.0,
                              ),
                              child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                AppText(
                                  'Total Active Members',
                                  style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                                const SizedBox(height: 6.0),
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      '124',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 22.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    Padding(
                                      padding: const EdgeInsets.fromLTRB(
                                        6.0,
                                        2.0,
                                        6.0,
                                        2.0,
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          '+8% MoM',
                                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 10.0),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            )),
                            const SizedBox(width: 20.0),
                            Expanded(child: Padding(
                              padding: const EdgeInsets.fromLTRB(
                                16.0,
                                16.0,
                                16.0,
                                16.0,
                              ),
                              child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                AppText(
                                  'New Registrations',
                                  style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                                const SizedBox(height: 6.0),
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      '28',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 22.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    Padding(
                                      padding: const EdgeInsets.fromLTRB(
                                        6.0,
                                        2.0,
                                        6.0,
                                        2.0,
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          '+14%',
                                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 10.0),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            )),
                            const SizedBox(width: 20.0),
                            Expanded(child: Padding(
                              padding: const EdgeInsets.fromLTRB(
                                16.0,
                                16.0,
                                16.0,
                                16.0,
                              ),
                              child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                AppText(
                                  'Client Retention Rate',
                                  style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                                const SizedBox(height: 6.0),
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      '94.2%',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 22.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    Padding(
                                      padding: const EdgeInsets.fromLTRB(
                                        6.0,
                                        2.0,
                                        6.0,
                                        2.0,
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Stable',
                                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 10.0),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            )),
                            const SizedBox(width: 20.0),
                            Expanded(child: Padding(
                              padding: const EdgeInsets.fromLTRB(
                                16.0,
                                16.0,
                                16.0,
                                16.0,
                              ),
                              child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                AppText(
                                  'Average Active Days',
                                  style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                                const SizedBox(height: 6.0),
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      '4.8 days',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 22.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    Padding(
                                      padding: const EdgeInsets.fromLTRB(
                                        6.0,
                                        2.0,
                                        6.0,
                                        2.0,
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Good',
                                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 10.0),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            )),
                          ],
                        ),
                        const SizedBox(height: 24.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            20.0,
                            20.0,
                            20.0,
                            20.0,
                          ),
                          child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            Padding(
                              padding: const EdgeInsets.fromLTRB(
                                0.0,
                                0.0,
                                0.0,
                                8.0,
                              ),
                              child: Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 24.0,
                                      height: 24.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        const SizedBox.shrink(),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 12.0),
                                    AppText(
                                      'Select All',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 14.0),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 12.0),
                                    AppText(
                                      '|',
                                      style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 12.0),
                                    AppText(
                                      '3 Clients Selected',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                  ],
                                ),
                                Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Padding(
                                      padding: const EdgeInsets.fromLTRB(
                                        12.0,
                                        6.0,
                                        12.0,
                                        6.0,
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Bulk Message',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 8.0),
                                    Padding(
                                      padding: const EdgeInsets.fromLTRB(
                                        12.0,
                                        6.0,
                                        12.0,
                                        6.0,
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Change Coach',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 8.0),
                                    Padding(
                                      padding: const EdgeInsets.fromLTRB(
                                        12.0,
                                        6.0,
                                        12.0,
                                        6.0,
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Assign Program',
                                          style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            ),
                            const SizedBox(height: 16.0),
                            Padding(
                              padding: const EdgeInsets.fromLTRB(
                                16.0,
                                4.0,
                                16.0,
                                8.0,
                              ),
                              child: Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                SizedBox(
                                  width: 24.0,
                                  child: Container(
                                  width: 24.0,
                                  height: 100.0,
                                  decoration: BoxDecoration(
                                    color: Colors.transparent,
                                    borderRadius: BorderRadius.circular(
                                      0.0,
                                    ),
                                  ),
                                ),
                                ),
                                const SizedBox(width: 20.0),
                                AppText(
                                  'CLIENT NAME',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.left,
                                ),
                                const SizedBox(width: 20.0),
                                AppText(
                                  'STATUS',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.left,
                                ),
                                const SizedBox(width: 20.0),
                                AppText(
                                  'ASSIGNED PLAN',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.left,
                                ),
                                const SizedBox(width: 20.0),
                                AppText(
                                  'LAST ACTIVE',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.left,
                                ),
                                const SizedBox(width: 20.0),
                                AppText(
                                  'NEXT APPOINTMENT',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.left,
                                ),
                                const SizedBox(width: 20.0),
                                AppText(
                                  'ACTIONS',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.right,
                                ),
                              ],
                            ),
                            ),
                            const SizedBox(height: 16.0),
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                Padding(
                                  padding: const EdgeInsets.fromLTRB(
                                    16.0,
                                    12.0,
                                    16.0,
                                    12.0,
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 24.0,
                                      height: 24.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        const SizedBox.shrink(),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 20.0),
                                    Expanded(child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Image.asset(
                                          rectangle3908,
                                          width: 32.0,
                                          height: 32.0,
                                          fit: BoxFit.fill,
                                        ),
                                        const SizedBox(width: 12.0),
                                        AppText(
                                          'Alex Rivera',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 14.0),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                    const SizedBox(width: 20.0),
                                    SizedBox(
                                      width: 120.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            8.0,
                                            2.0,
                                            8.0,
                                            2.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Active',
                                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist', fontSize: 12.0),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Hypertrophy V3',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Today',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Tomorrow, 9:00 AM',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    SizedBox(
                                      width: 180.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.end,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            10.0,
                                            6.0,
                                            10.0,
                                            6.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Message',
                                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                        const SizedBox(width: 8.0),
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            10.0,
                                            6.0,
                                            10.0,
                                            6.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Profile',
                                              style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w700),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                      ],
                                    ),
                                    ),
                                  ],
                                ),
                                ),
                                Padding(
                                  padding: const EdgeInsets.fromLTRB(
                                    16.0,
                                    12.0,
                                    16.0,
                                    12.0,
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 24.0,
                                      height: 24.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        const SizedBox.shrink(),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 20.0),
                                    Expanded(child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Image.asset(
                                          rectangle3925,
                                          width: 32.0,
                                          height: 32.0,
                                          fit: BoxFit.fill,
                                        ),
                                        const SizedBox(width: 12.0),
                                        AppText(
                                          'Jessica Smith',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 14.0),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                    const SizedBox(width: 20.0),
                                    SizedBox(
                                      width: 120.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            8.0,
                                            2.0,
                                            8.0,
                                            2.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'New',
                                              style: TextStyle(color: const Color(0xFF007AFF), fontFamily: 'Geist', fontSize: 12.0),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Keto Weightloss 8W',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Yesterday',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Today, 5:00 PM',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    SizedBox(
                                      width: 180.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.end,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            10.0,
                                            6.0,
                                            10.0,
                                            6.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Message',
                                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                        const SizedBox(width: 8.0),
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            10.0,
                                            6.0,
                                            10.0,
                                            6.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Profile',
                                              style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w700),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                      ],
                                    ),
                                    ),
                                  ],
                                ),
                                ),
                                Padding(
                                  padding: const EdgeInsets.fromLTRB(
                                    16.0,
                                    12.0,
                                    16.0,
                                    12.0,
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 24.0,
                                      height: 24.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        const SizedBox.shrink(),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 20.0),
                                    Expanded(child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Image.asset(
                                          rectangle3942,
                                          width: 32.0,
                                          height: 32.0,
                                          fit: BoxFit.fill,
                                        ),
                                        const SizedBox(width: 12.0),
                                        AppText(
                                          'Brandon Cooper',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 14.0),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                    const SizedBox(width: 20.0),
                                    SizedBox(
                                      width: 120.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            8.0,
                                            2.0,
                                            8.0,
                                            2.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Active',
                                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist', fontSize: 12.0),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Premium Powerbuilding V3',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      '2 days ago',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Thursday, 2:00 PM',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    SizedBox(
                                      width: 180.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.end,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            10.0,
                                            6.0,
                                            10.0,
                                            6.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Message',
                                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                        const SizedBox(width: 8.0),
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            10.0,
                                            6.0,
                                            10.0,
                                            6.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Profile',
                                              style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w700),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                      ],
                                    ),
                                    ),
                                  ],
                                ),
                                ),
                                Padding(
                                  padding: const EdgeInsets.fromLTRB(
                                    16.0,
                                    12.0,
                                    16.0,
                                    12.0,
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 24.0,
                                      height: 24.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        const SizedBox.shrink(),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 20.0),
                                    Expanded(child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Image.asset(
                                          rectangle3959,
                                          width: 32.0,
                                          height: 32.0,
                                          fit: BoxFit.fill,
                                        ),
                                        const SizedBox(width: 12.0),
                                        AppText(
                                          'Elena Rostova',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 14.0),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                    const SizedBox(width: 20.0),
                                    SizedBox(
                                      width: 120.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            8.0,
                                            2.0,
                                            8.0,
                                            2.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Paused',
                                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 12.0),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Muscle Gain Basic',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      '1 week ago',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Pending resume',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    SizedBox(
                                      width: 180.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.end,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            10.0,
                                            6.0,
                                            10.0,
                                            6.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Message',
                                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                        const SizedBox(width: 8.0),
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            10.0,
                                            6.0,
                                            10.0,
                                            6.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Profile',
                                              style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w700),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                      ],
                                    ),
                                    ),
                                  ],
                                ),
                                ),
                                Padding(
                                  padding: const EdgeInsets.fromLTRB(
                                    16.0,
                                    12.0,
                                    16.0,
                                    12.0,
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 24.0,
                                      height: 24.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        const SizedBox.shrink(),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 20.0),
                                    Expanded(child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Image.asset(
                                          rectangle3976,
                                          width: 32.0,
                                          height: 32.0,
                                          fit: BoxFit.fill,
                                        ),
                                        const SizedBox(width: 12.0),
                                        AppText(
                                          'Tyler Durden',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 14.0),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                    const SizedBox(width: 20.0),
                                    SizedBox(
                                      width: 120.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            8.0,
                                            2.0,
                                            8.0,
                                            2.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Active',
                                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist', fontSize: 12.0),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                      ],
                                    ),
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Combat Shred & Cardio',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Today',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    AppText(
                                      'Today, 7:00 PM',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(width: 20.0),
                                    SizedBox(
                                      width: 180.0,
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.end,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            10.0,
                                            6.0,
                                            10.0,
                                            6.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Message',
                                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                        const SizedBox(width: 8.0),
                                        Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                            10.0,
                                            6.0,
                                            10.0,
                                            6.0,
                                          ),
                                          child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            AppText(
                                              'Profile',
                                              style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w700),
                                              textAlign: TextAlign.left,
                                            ),
                                          ],
                                        ),
                                        ),
                                      ],
                                    ),
                                    ),
                                  ],
                                ),
                                ),
                              ],
                            ),
                          ],
                        ),
                        ),
                      ],
                    ),
                    ),
                  ],
                )),
              ],
            ),
          ],
        ),
        ),
      ),
    );
  }
}
