// GENERATED FILE - DO NOT EDIT BY HAND
// Generated by design_codegen from the Galaxy Figma plugin tokens JSON.

import 'package:flutter/material.dart';
import 'package:design_system/design_system.dart';
import '../../../../../generated/routes/app_router.dart';
import '../../../../../generated/constants/assets_path.dart';

class ProgressSharing extends StatelessWidget {
  const ProgressSharing({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: context.ds.backgroundPrimary,
      body: SafeArea(
        child: SingleChildScrollView(
          child: Container(
          decoration: BoxDecoration(
            color: const Color(0xFF08090C),
          ),
          child: Row(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(
              width: 260.0,
              child: Container(
              padding: const EdgeInsets.fromLTRB(16.0, 24.0, 16.0, 24.0),
              decoration: BoxDecoration(
                color: const Color(0xFF12141C),
                border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
              ),
              child: Column(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Padding(
                  padding: const EdgeInsets.fromLTRB(12.0, 0.0, 0.0, 28.0),
                  child: Row(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    SizedBox(
                      width: 28.0,
                      height: 28.0,
                      child: Container(
                      decoration: BoxDecoration(
                        color: const Color(0xFFD2FF00),
                        borderRadius: BorderRadius.circular(RadiusTokens.radius6),
                      ),
                      child: Column(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                      ],
                    ),
                    ),
                    ),
                    const SizedBox(width: 8.0),
                    AppText(
                      'FitPro',
                      style: TextStyle(color: context.ds.textPrimary, fontFamily: 'Outfit', fontSize: 20.0, letterSpacing: -1.0),
                      textAlign: TextAlign.left,
                    ),
                    const SizedBox(width: 8.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(6.0, 2.0, 6.0, 2.0),
                      decoration: BoxDecoration(
                        color: const Color(0x12FFFFFF),
                        borderRadius: BorderRadius.circular(RadiusTokens.radius4),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        AppText(
                          'SaaS',
                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 10.0),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                  ],
                ),
                ),
                Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Diet Plan',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Workouts Programs',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                      decoration: BoxDecoration(
                        color: const Color(0x1AD2FF00),
                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Container(
                        width: 18.0,
                        height: 18.0,
                        color: Colors.transparent,
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Progress Sharing',
                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist', fontSize: 14.0),
                          textAlign: TextAlign.left,
                        ),
                        const SizedBox(width: 12.0),
                        Container(
                          width: 6.0,
                          height: 6.0,
                          decoration: BoxDecoration(
                            color: const Color(0xFFD2FF00),
                            shape: BoxShape.circle,
                          ),
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Client Management',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Subscription',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Client Profile',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Leads Management',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Business Growth',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Unlimited Co-workers',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Custom Branding',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Container(
                      padding: const EdgeInsets.fromLTRB(12.0, 10.0, 12.0, 10.0),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Reports',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                  ],
                ),
                const SizedBox(height: 402.0),
                Container(
                  padding: const EdgeInsets.fromLTRB(12.0, 12.0, 12.0, 12.0),
                  decoration: BoxDecoration(
                    color: const Color(0x05FFFFFF),
                    borderRadius: BorderRadius.circular(RadiusTokens.radius12),
                    border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                  ),
                  child: Row(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Image.asset(
                      rectangle3502,
                      width: 36.0,
                      height: 36.0,
                      fit: BoxFit.fill,
                    ),
                    const SizedBox(width: 12.0),
                    Expanded(child: Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        AppText(
                          'Coach Marcus',
                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 13.0),
                          textAlign: TextAlign.left,
                        ),
                        const SizedBox(height: 2.0),
                        AppText(
                          'HEAD TRAINER',
                          style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    )),
                  ],
                ),
                ),
              ],
            ),
            ),
            ),
            Expanded(child: Column(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Container(
                  padding: const EdgeInsets.fromLTRB(32.0, 16.0, 32.0, 16.0),
                  decoration: BoxDecoration(
                    border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                  ),
                  child: Row(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        AppText(
                          'Client Progress & Portals',
                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 24.0),
                          textAlign: TextAlign.left,
                        ),
                        const SizedBox(height: 4.0),
                        AppText(
                          'Operator Dashboard',
                          style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        SizedBox(
                          width: 220.0,
                          child: Container(
                          padding: const EdgeInsets.fromLTRB(12.0, 8.0, 12.0, 8.0),
                          decoration: BoxDecoration(
                            color: const Color(0x08FFFFFF),
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                            border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 8.0),
                            AppText(
                              'Search clients...',
                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        ),
                        const SizedBox(width: 16.0),
                        SizedBox(
                          width: 36.0,
                          height: 36.0,
                          child: Container(
                          decoration: BoxDecoration(
                            color: const Color(0x05FFFFFF),
                            borderRadius: BorderRadius.circular(RadiusTokens.radius18),
                            border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            Container(
                              width: 8.0,
                              height: 8.0,
                              decoration: BoxDecoration(
                                color: const Color(0xFFD2FF00),
                                shape: BoxShape.circle,
                                border: Border.all(color: const Color(0xFF12141C), width: 1.5),
                              ),
                            ),
                          ],
                        ),
                        ),
                        ),
                        const SizedBox(width: 16.0),
                        Container(
                          padding: const EdgeInsets.fromLTRB(16.0, 8.0, 16.0, 8.0),
                          decoration: BoxDecoration(
                            color: const Color(0xFFD2FF00),
                            borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 6.0),
                            AppText(
                              'Quick Assign',
                              style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w700),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
                ),
                Padding(
                  padding: const EdgeInsets.fromLTRB(32.0, 32.0, 32.0, 32.0),
                  child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        SizedBox(
                          width: 480.0,
                          child: Container(
                          padding: const EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 20.0),
                          decoration: BoxDecoration(
                            color: const Color(0xFF12141C),
                            borderRadius: BorderRadius.circular(RadiusTokens.radius16),
                            border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                          ),
                          child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                AppText(
                                  'Before / After Comparison',
                                  style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 16.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.left,
                                ),
                                AppText(
                                  'Client: Alex Rivera',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 12.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                              ],
                            ),
                            const SizedBox(height: 16.0),
                            Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Expanded(child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.stretch,
                                  children: [
                                    Image.asset(
                                      rectangle3529,
                                      width: 214.0,
                                      height: 240.0,
                                      fit: BoxFit.fill,
                                    ),
                                    const SizedBox(height: 10.0),
                                    Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        AppText(
                                          'WEEK 1 (START)',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Outfit', fontSize: 12.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          '92.4 kg  •  24% BF',
                                          style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                  ],
                                )),
                                const SizedBox(width: 12.0),
                                Expanded(child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.stretch,
                                  children: [
                                    Image.asset(
                                      rectangle3534,
                                      width: 214.0,
                                      height: 240.0,
                                      fit: BoxFit.fill,
                                    ),
                                    const SizedBox(height: 10.0),
                                    Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        AppText(
                                          'WEEK 12 (NOW)',
                                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Outfit', fontSize: 12.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          '84.1 kg  •  14% BF',
                                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                  ],
                                )),
                              ],
                            ),
                          ],
                        ),
                        ),
                        ),
                        const SizedBox(width: 20.0),
                        Expanded(child: Container(
                          padding: const EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 20.0),
                          decoration: BoxDecoration(
                            color: const Color(0xFF12141C),
                            borderRadius: BorderRadius.circular(RadiusTokens.radius16),
                            border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                          ),
                          child: Column(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                AppText(
                                  'Weight & Fat Percentage Trend',
                                  style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 16.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.left,
                                ),
                                Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 8.0,
                                          height: 8.0,
                                          decoration: BoxDecoration(
                                            color: const Color(0xFFD2FF00),
                                            shape: BoxShape.circle,
                                          ),
                                        ),
                                        const SizedBox(width: 6.0),
                                        AppText(
                                          'Weight (kg)',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                    const SizedBox(width: 12.0),
                                    Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 8.0,
                                          height: 8.0,
                                          decoration: BoxDecoration(
                                            color: const Color(0xFF007AFF),
                                            shape: BoxShape.circle,
                                          ),
                                        ),
                                        const SizedBox(width: 6.0),
                                        AppText(
                                          'Body Fat %',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            const SizedBox(height: 16.0),
                            SizedBox(
                              height: 200.0,
                              child: Column(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                SizedBox(
                                  width: 576.0,
                                  height: 200.0,
                                  child: Column(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      width: 576.0,
                                      height: 1.0,
                                      color: const Color(0xFF1C1F2B),
                                    ),
                                    Container(
                                      width: 576.0,
                                      height: 1.0,
                                      color: const Color(0xFF1C1F2B),
                                    ),
                                    Container(
                                      width: 576.0,
                                      height: 1.0,
                                      color: const Color(0xFF1C1F2B),
                                    ),
                                    Container(
                                      width: 576.0,
                                      height: 1.0,
                                      color: const Color(0xFF1C1F2B),
                                    ),
                                  ],
                                ),
                                ),
                                SizedBox(
                                  width: 576.0,
                                  height: 200.0,
                                  child: Column(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      width: 150.0,
                                      height: 3.0,
                                      color: const Color(0xFFD2FF00),
                                    ),
                                    Container(
                                      width: 140.0,
                                      height: 3.0,
                                      color: const Color(0xFFD2FF00),
                                    ),
                                    Container(
                                      width: 160.0,
                                      height: 3.0,
                                      color: const Color(0xFFD2FF00),
                                    ),
                                    Container(
                                      width: 120.0,
                                      height: 3.0,
                                      color: const Color(0xFFD2FF00),
                                    ),
                                    Container(
                                      width: 10.0,
                                      height: 10.0,
                                      decoration: BoxDecoration(
                                        color: const Color(0xFFD2FF00),
                                        shape: BoxShape.circle,
                                        border: Border.all(color: const Color(0xFF12141C), width: 2.0),
                                      ),
                                    ),
                                    Container(
                                      width: 10.0,
                                      height: 10.0,
                                      decoration: BoxDecoration(
                                        color: const Color(0xFFD2FF00),
                                        shape: BoxShape.circle,
                                        border: Border.all(color: const Color(0xFF12141C), width: 2.0),
                                      ),
                                    ),
                                  ],
                                ),
                                ),
                              ],
                            ),
                            ),
                            const SizedBox(height: 16.0),
                            Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                AppText(
                                  'Week 1',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                                AppText(
                                  'Week 4',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                                AppText(
                                  'Week 8',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                                AppText(
                                  'Week 12',
                                  style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                              ],
                            ),
                          ],
                        ),
                        )),
                      ],
                    ),
                    const SizedBox(height: 24.0),
                    Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Expanded(child: Container(
                          padding: const EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 20.0),
                          decoration: BoxDecoration(
                            color: const Color(0xFF12141C),
                            borderRadius: BorderRadius.circular(RadiusTokens.radius16),
                            border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                          ),
                          child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            AppText(
                              'Unlocked Achievements',
                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 16.0, fontWeight: FontWeight.w700),
                              textAlign: TextAlign.left,
                            ),
                            const SizedBox(height: 16.0),
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                Container(
                                  padding: const EdgeInsets.fromLTRB(10.0, 10.0, 10.0, 10.0),
                                  decoration: BoxDecoration(
                                    color: const Color(0xFF08090C),
                                    borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 36.0,
                                      height: 36.0,
                                      child: Container(
                                      decoration: BoxDecoration(
                                        color: const Color(0x1AD2FF00),
                                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            const AppIcon(Icons.circle),
                                          ],
                                        ),
                                      ],
                                    ),
                                    ),
                                    ),
                                    const SizedBox(width: 12.0),
                                    Expanded(child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Iron Warrior',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          '100 Workouts Completed',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                  ],
                                ),
                                ),
                                const SizedBox(height: 12.0),
                                Container(
                                  padding: const EdgeInsets.fromLTRB(10.0, 10.0, 10.0, 10.0),
                                  decoration: BoxDecoration(
                                    color: const Color(0xFF08090C),
                                    borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 36.0,
                                      height: 36.0,
                                      child: Container(
                                      decoration: BoxDecoration(
                                        color: const Color(0x1AD2FF00),
                                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            const AppIcon(Icons.circle),
                                          ],
                                        ),
                                      ],
                                    ),
                                    ),
                                    ),
                                    const SizedBox(width: 12.0),
                                    Expanded(child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Calorie Deficit King',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          'Streak of 30 days hit',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                  ],
                                ),
                                ),
                                const SizedBox(height: 12.0),
                                Container(
                                  padding: const EdgeInsets.fromLTRB(10.0, 10.0, 10.0, 10.0),
                                  decoration: BoxDecoration(
                                    color: const Color(0xFF08090C),
                                    borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 36.0,
                                      height: 36.0,
                                      child: Container(
                                      decoration: BoxDecoration(
                                        color: const Color(0x1AD2FF00),
                                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            const AppIcon(Icons.circle),
                                          ],
                                        ),
                                      ],
                                    ),
                                    ),
                                    ),
                                    const SizedBox(width: 12.0),
                                    Expanded(child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Peak Hydration',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          'Daily intake goal met',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                  ],
                                ),
                                ),
                                const SizedBox(height: 12.0),
                                Container(
                                  padding: const EdgeInsets.fromLTRB(10.0, 10.0, 10.0, 10.0),
                                  decoration: BoxDecoration(
                                    color: const Color(0xFF08090C),
                                    borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 36.0,
                                      height: 36.0,
                                      child: Container(
                                      decoration: BoxDecoration(
                                        color: const Color(0x1AD2FF00),
                                        borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            const AppIcon(Icons.circle),
                                          ],
                                        ),
                                      ],
                                    ),
                                    ),
                                    ),
                                    const SizedBox(width: 12.0),
                                    Expanded(child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          'Consistency Master',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          'Zero sessions missed',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                  ],
                                ),
                                ),
                              ],
                            ),
                          ],
                        ),
                        )),
                        const SizedBox(width: 20.0),
                        SizedBox(
                          width: 420.0,
                          child: Container(
                          padding: const EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 20.0),
                          decoration: BoxDecoration(
                            color: const Color(0xFF12141C),
                            borderRadius: BorderRadius.circular(RadiusTokens.radius16),
                            border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                          ),
                          child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            AppText(
                              'Client Portal Link',
                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 16.0, fontWeight: FontWeight.w700),
                              textAlign: TextAlign.left,
                            ),
                            const SizedBox(height: 16.0),
                            Container(
                              padding: const EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 16.0),
                              decoration: BoxDecoration(
                                color: const Color(0xFF08090C),
                                borderRadius: BorderRadius.circular(RadiusTokens.radius12),
                                border: Border.all(color: const Color(0xFF1C1F2B), width: 1.0),
                              ),
                              child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      'PORTAL ACTIVE',
                                      style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 10.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        const AppIcon(Icons.circle),
                                      ],
                                    ),
                                  ],
                                ),
                                const SizedBox(height: 12.0),
                                Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    AppText(
                                      'fitpro.co/portal/alex-rivera-12w',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    const SizedBox(height: 4.0),
                                    AppText(
                                      'Private client progress and coaching dashboard.',
                                      style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            ),
                            const SizedBox(height: 16.0),
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      'Enable Client Sharing Portal',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    SizedBox(
                                      width: 36.0,
                                      height: 20.0,
                                      child: Container(
                                      padding: const EdgeInsets.fromLTRB(18.0, 0.0, 0.0, 0.0),
                                      decoration: BoxDecoration(
                                        color: const Color(0xFFD2FF00),
                                        borderRadius: BorderRadius.circular(RadiusTokens.radius10),
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 14.0,
                                          height: 14.0,
                                          decoration: BoxDecoration(
                                            color: const Color(0xFF000000),
                                            shape: BoxShape.circle,
                                          ),
                                        ),
                                      ],
                                    ),
                                    ),
                                    ),
                                  ],
                                ),
                                const SizedBox(height: 12.0),
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      'Auto-Post Milestones to Team Channel',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    SizedBox(
                                      width: 36.0,
                                      height: 20.0,
                                      child: Container(
                                      padding: const EdgeInsets.fromLTRB(2.0, 0.0, 0.0, 0.0),
                                      decoration: BoxDecoration(
                                        color: const Color(0xFF1C1F2B),
                                        borderRadius: BorderRadius.circular(RadiusTokens.radius10),
                                      ),
                                      child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 14.0,
                                          height: 14.0,
                                          decoration: BoxDecoration(
                                            color: const Color(0xFF545766),
                                            shape: BoxShape.circle,
                                          ),
                                        ),
                                      ],
                                    ),
                                    ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            const SizedBox(height: 16.0),
                            Container(
                              padding: const EdgeInsets.fromLTRB(12.0, 12.0, 12.0, 12.0),
                              decoration: BoxDecoration(
                                color: const Color(0xFFD2FF00),
                                borderRadius: BorderRadius.circular(RadiusTokens.radius8),
                              ),
                              child: Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                AppText(
                                  'Generate Report PDF',
                                  style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.left,
                                ),
                              ],
                            ),
                            ),
                          ],
                        ),
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
                ),
              ],
            )),
          ],
        ),
        ),
        ),
      ),
    );
  }
}
