// GENERATED FILE - DO NOT EDIT BY HAND
// Generated by design_codegen from the Galaxy Figma plugin tokens JSON.

import 'package:flutter/material.dart';
import 'package:design_system/design_system.dart';
import '../../../../../generated/routes/app_router.dart';
import '../../../../../generated/constants/assets_path.dart';

class WorkoutsPrograms extends StatelessWidget {
  const WorkoutsPrograms({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: context.ds.backgroundPrimary,
      body: SafeArea(
        child: SingleChildScrollView(
          child: Row(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(
              width: 260.0,
              child: Padding(
              padding: const EdgeInsets.fromLTRB(
                16.0,
                24.0,
                16.0,
                24.0,
              ),
              child: Column(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Padding(
                  padding: const EdgeInsets.fromLTRB(
                    12.0,
                    0.0,
                    0.0,
                    28.0,
                  ),
                  child: Row(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    SizedBox(
                      width: 28.0,
                      height: 28.0,
                      child: Column(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(width: 8.0),
                    AppText(
                      'FitPro',
                      style: TextStyle(color: context.ds.textPrimary, fontFamily: 'Outfit', fontSize: 20.0, letterSpacing: -1.0),
                      textAlign: TextAlign.left,
                    ),
                    const SizedBox(width: 8.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        6.0,
                        2.0,
                        6.0,
                        2.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        AppText(
                          'SaaS',
                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 10.0),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                  ],
                ),
                ),
                Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        10.0,
                        12.0,
                        10.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Diet Plan',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        10.0,
                        12.0,
                        10.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Workouts Programs',
                          style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist', fontSize: 14.0),
                          textAlign: TextAlign.left,
                        ),
                        const SizedBox(width: 12.0),
                        const SizedBox.shrink(),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        10.0,
                        12.0,
                        10.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Container(
                        width: 18.0,
                        height: 18.0,
                        color: Colors.transparent,
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Progress Sharing',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        10.0,
                        12.0,
                        10.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Client Management',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        10.0,
                        12.0,
                        10.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Subscription',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        10.0,
                        12.0,
                        10.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Client Profile',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        10.0,
                        12.0,
                        10.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Leads Management',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        10.0,
                        12.0,
                        10.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Business Growth',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        10.0,
                        12.0,
                        10.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Unlimited Co-workers',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        10.0,
                        12.0,
                        10.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Custom Branding',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                    const SizedBox(height: 4.0),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(
                        12.0,
                        10.0,
                        12.0,
                        10.0,
                      ),
                      child: Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const AppIcon(Icons.circle),
                          ],
                        ),
                        const SizedBox(width: 12.0),
                        AppText(
                          'Reports',
                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 14.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    ),
                  ],
                ),
                const SizedBox(height: 402.0),
                Padding(
                  padding: const EdgeInsets.fromLTRB(
                    12.0,
                    12.0,
                    12.0,
                    12.0,
                  ),
                  child: Row(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Image.asset(
                      rectangle3345,
                      width: 36.0,
                      height: 36.0,
                      fit: BoxFit.fill,
                    ),
                    const SizedBox(width: 12.0),
                    Expanded(child: Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        AppText(
                          'Coach Marcus',
                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Geist', fontSize: 13.0),
                          textAlign: TextAlign.left,
                        ),
                        const SizedBox(height: 2.0),
                        AppText(
                          'HEAD TRAINER',
                          style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    )),
                  ],
                ),
                ),
              ],
            ),
            ),
            ),
            Expanded(child: Column(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Padding(
                  padding: const EdgeInsets.fromLTRB(
                    32.0,
                    16.0,
                    32.0,
                    16.0,
                  ),
                  child: Row(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        AppText(
                          'Workout Program Library',
                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 24.0),
                          textAlign: TextAlign.left,
                        ),
                        const SizedBox(height: 4.0),
                        AppText(
                          'Operator Dashboard',
                          style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                          textAlign: TextAlign.left,
                        ),
                      ],
                    ),
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        SizedBox(
                          width: 220.0,
                          child: Padding(
                          padding: const EdgeInsets.fromLTRB(
                            12.0,
                            8.0,
                            12.0,
                            8.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 8.0),
                            AppText(
                              'Search clients...',
                              style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        ),
                        const SizedBox(width: 16.0),
                        SizedBox(
                          width: 36.0,
                          height: 36.0,
                          child: Row(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox.shrink(),
                          ],
                        ),
                        ),
                        const SizedBox(width: 16.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            16.0,
                            8.0,
                            16.0,
                            8.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const AppIcon(Icons.circle),
                              ],
                            ),
                            const SizedBox(width: 6.0),
                            AppText(
                              'Quick Assign',
                              style: TextStyle(color: const Color(0xFF000000), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w700),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
                ),
                Padding(
                  padding: const EdgeInsets.fromLTRB(
                    32.0,
                    32.0,
                    32.0,
                    32.0,
                  ),
                  child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Image.asset(
                      frame3365,
                      width: 1116.0,
                      height: 212.0,
                      fit: BoxFit.fill,
                    ),
                    const SizedBox(height: 24.0),
                    Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            14.0,
                            8.0,
                            14.0,
                            8.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText(
                              'All Programs',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(width: 8.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            14.0,
                            8.0,
                            14.0,
                            8.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText(
                              'Strength',
                              style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist', fontSize: 13.0),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(width: 8.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            14.0,
                            8.0,
                            14.0,
                            8.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText(
                              'Cardio',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(width: 8.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            14.0,
                            8.0,
                            14.0,
                            8.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText(
                              'Flexibility',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                        const SizedBox(width: 8.0),
                        Padding(
                          padding: const EdgeInsets.fromLTRB(
                            14.0,
                            8.0,
                            14.0,
                            8.0,
                          ),
                          child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText(
                              'HIIT',
                              style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                              textAlign: TextAlign.left,
                            ),
                          ],
                        ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 24.0),
                    Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        SizedBox(
                          width: 420.0,
                          child: Padding(
                          padding: const EdgeInsets.fromLTRB(
                            20.0,
                            20.0,
                            20.0,
                            20.0,
                          ),
                          child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            Row(
                              mainAxisSize: MainAxisSize.max,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                AppText(
                                  'Session Timeline',
                                  style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 16.0, fontWeight: FontWeight.w700),
                                  textAlign: TextAlign.left,
                                ),
                                AppText(
                                  '60 Mins Total',
                                  style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 12.0, fontWeight: FontWeight.w400),
                                  textAlign: TextAlign.left,
                                ),
                              ],
                            ),
                            const SizedBox(height: 16.0),
                            Padding(
                              padding: const EdgeInsets.fromLTRB(
                                8.0,
                                0.0,
                                0.0,
                                0.0,
                              ),
                              child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Column(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        const SizedBox.shrink(),
                                        const SizedBox(height: 4.0),
                                        Container(
                                          width: 44.0,
                                          
                                          decoration: BoxDecoration(
                                            color: Colors.transparent,
                                            borderRadius: BorderRadius.circular(
                                              0.0,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                    const SizedBox(width: 12.0),
                                    Expanded(child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          '00:00',
                                          style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          'Dynamic Warmup',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          'World\'s greatest stretch & arm circles',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                  ],
                                ),
                                const SizedBox(height: 16.0),
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Column(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        const SizedBox.shrink(),
                                        const SizedBox(height: 4.0),
                                        Container(
                                          width: 44.0,
                                          
                                          decoration: BoxDecoration(
                                            color: Colors.transparent,
                                            borderRadius: BorderRadius.circular(
                                              0.0,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                    const SizedBox(width: 12.0),
                                    Expanded(child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          '08:00',
                                          style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          'A1: Back Squat',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          'Heavy mechanical tension sets',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                  ],
                                ),
                                const SizedBox(height: 16.0),
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Column(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        const SizedBox.shrink(),
                                        const SizedBox(height: 4.0),
                                        Container(
                                          width: 44.0,
                                          
                                          decoration: BoxDecoration(
                                            color: Colors.transparent,
                                            borderRadius: BorderRadius.circular(
                                              0.0,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                    const SizedBox(width: 12.0),
                                    Expanded(child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          '25:00',
                                          style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          'B1: Romanian Deadlift',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          'Posterior chain hypertrophy focus',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                  ],
                                ),
                                const SizedBox(height: 16.0),
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Column(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        const SizedBox.shrink(),
                                      ],
                                    ),
                                    const SizedBox(width: 12.0),
                                    Expanded(child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        AppText(
                                          '40:00',
                                          style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 11.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          'C1: Hanging Knee Raise',
                                          style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                          textAlign: TextAlign.left,
                                        ),
                                        const SizedBox(height: 2.0),
                                        AppText(
                                          'Strict execution, core stabilization',
                                          style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 12.0, fontWeight: FontWeight.w400),
                                          textAlign: TextAlign.left,
                                        ),
                                      ],
                                    )),
                                  ],
                                ),
                              ],
                            ),
                            ),
                          ],
                        ),
                        ),
                        ),
                        const SizedBox(width: 20.0),
                        Expanded(child: Padding(
                          padding: const EdgeInsets.fromLTRB(
                            20.0,
                            20.0,
                            20.0,
                            20.0,
                          ),
                          child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            AppText(
                              'Exercise Prescription',
                              style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 16.0, fontWeight: FontWeight.w700),
                              textAlign: TextAlign.left,
                            ),
                            const SizedBox(height: 16.0),
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                Padding(
                                  padding: const EdgeInsets.fromLTRB(
                                    0.0,
                                    0.0,
                                    0.0,
                                    10.0,
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    AppText(
                                      'EXERCISE',
                                      style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 12.0),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      'SETS',
                                      style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 12.0),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      'REPS',
                                      style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 12.0),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      'INTENSITY',
                                      style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 12.0),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      'REST',
                                      style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist', fontSize: 12.0),
                                      textAlign: TextAlign.right,
                                    ),
                                  ],
                                ),
                                ),
                                Padding(
                                  padding: const EdgeInsets.fromLTRB(
                                    0.0,
                                    12.0,
                                    0.0,
                                    12.0,
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      'A1. Barbell Back Squat',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '4',
                                      style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '6-8 reps',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      'RPE 8.5',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '3 min',
                                      style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.right,
                                    ),
                                  ],
                                ),
                                ),
                                Padding(
                                  padding: const EdgeInsets.fromLTRB(
                                    0.0,
                                    12.0,
                                    0.0,
                                    12.0,
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      'B1. Dumbbell Romanian Deadlift',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '3',
                                      style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '8-10 reps',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      'RPE 8',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '2 min',
                                      style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.right,
                                    ),
                                  ],
                                ),
                                ),
                                Padding(
                                  padding: const EdgeInsets.fromLTRB(
                                    0.0,
                                    12.0,
                                    0.0,
                                    12.0,
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      'B2. Bulgerian Split Squat',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '3',
                                      style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '10-12 ea',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      'RPE 9',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '90 sec',
                                      style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.right,
                                    ),
                                  ],
                                ),
                                ),
                                Padding(
                                  padding: const EdgeInsets.fromLTRB(
                                    0.0,
                                    12.0,
                                    0.0,
                                    12.0,
                                  ),
                                  child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    AppText(
                                      'C1. Cable Pull-Through',
                                      style: TextStyle(color: const Color(0xFFFFFFFF), fontFamily: 'Outfit', fontSize: 14.0, fontWeight: FontWeight.w700),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '3',
                                      style: TextStyle(color: const Color(0xFFD2FF00), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '12-15 reps',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      'RPE 8',
                                      style: TextStyle(color: const Color(0xFF9296A8), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.left,
                                    ),
                                    AppText(
                                      '60 sec',
                                      style: TextStyle(color: const Color(0xFF545766), fontFamily: 'Geist Mono', fontSize: 13.0, fontWeight: FontWeight.w400),
                                      textAlign: TextAlign.right,
                                    ),
                                  ],
                                ),
                                ),
                              ],
                            ),
                          ],
                        ),
                        )),
                      ],
                    ),
                  ],
                ),
                ),
              ],
            )),
          ],
        ),
        ),
      ),
    );
  }
}
