#!/usr/bin/env bash
# GENERATED BY GALAXY - safe to customize, Galaxy will not overwrite it.
#
# 1. Design system  -> packages/design_system/lib
# 2. Pages + routes -> <app>/lib/generated/{pages,routes}
#
# Usage: bash scripts/generate_design.sh [tokens.json] [dsOut] [pagesOut]
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOKENS="${1:-token_pipeline/token.json}"
DS_OUT="${2:-packages/design_system/lib}"
PAGES_OUT="${3:-apps/fit_web_app/lib/generated/pages}"

if [ ! -f "$ROOT/$TOKENS" ]; then
  echo "Token file not found: $TOKENS" >&2
  exit 66
fi

cd "$ROOT/tools/design_codegen_runner"
dart pub get

dart run design_codegen:generate_design_system \
  "$ROOT/$TOKENS" \
  "$ROOT/$DS_OUT" \
  "$ROOT/$PAGES_OUT"
